# Generated by Django 5.0.4 on 2024-05-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default='../media/img/peperoni.jpeg', upload_to='media/img'),
        ),
    ]
