# Generated by Django 5.0.3 on 2024-05-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ингредиент')),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание пиццы'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(upload_to='pizza_images/', verbose_name='Изображение пиццы'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название пиццы'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена пиццы'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='main.ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
