# Generated by Django 5.0.3 on 2024-05-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_pizza_ingredients_alter_pizza_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='По умолчанию'),
        ),
    ]
