# Generated by Django 5.0.3 on 2024-05-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_order_delivery_time_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(choices=[('Сейчас', 'Сейчас'), ('Через 30 минут', 'Через 30 минут'), ('Через 1 час', 'Через 1 час'), ('Другое время', 'Другое время')], default='Сейчас', max_length=20),
        ),
    ]
