# Generated by Django 5.0.3 on 2024-05-22 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_order_custom_delivery_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
    ]
