# Generated by Django 5.0.3 on 2024-05-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_order_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='main.ingredient', verbose_name='Удаленные ингредиенты'),
        ),
    ]
